#!/bin/bash

gnome-terminal --title=geppetto -x $FLIGHTLINK_ROOT/JunkDrawer/shell_scripts/geppetto
gnome-terminal --title=cr_daemon -x $FLIGHTLINK_ROOT/JunkDrawer/shell_scripts/cr
gnome-terminal --title=cr_web -x $FLIGHTLINK_ROOT/JunkDrawer/shell_scripts/cr_web

#sleep 15
#firefox "http://localhost:3000"
