#!/usr/bin/ruby
require 'cgi'
require 'rexml/document'
require 'rexml/streamlistener'

class ReleaseNoter
	include REXML

	@@project_id = 194309
	@@token = '433b1f98512a7bfe96857531c6c84aca'

	def self.story(story_number)
		begin
			cmd = `curl -s -H "X-TrackerToken: #{@@token}" -X GET http://www.pivotaltracker.com/services/v3/projects/#{@@project_id}/stories/#{story_number}`
			xmldoc = Document.new(cmd)
			create_html xmldoc.elements["story"]			
		rescue Exception => e
			puts "Error occurred: #{e.message}"
		end
	end

	def self.create_html(node)
		name = CGI::escapeHTML(node.elements["name"].text)
		url = node.elements['url']
		puts "<li><a href='#{url.text}'>#{name}</a></li>"
	end
end

if ARGV[0]
	ReleaseNoter.story(ARGV[0]) 
else
	puts "Usage: release_noter <pivotal story id>"
end
